In [2]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import StrMethodFormatter
import matplotlib.ticker as mtick
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score
from sklearn.metrics import classification_report
import pickle 


import warnings
warnings.filterwarnings('ignore')
plt.style.use('seaborn')
%matplotlib inline

# set default plot size
plt.rcParams["figure.figsize"] = (15,8)
recruit = pd.read_csv('/home/shradhayaryan/CampusPlacementPrediction/train.csv')
recruit.head()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,0,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,0,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,0,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,0,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,0,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0

In [3]:
recruit = pd.read_csv('/home/shradhayaryan/CampusPlacementPrediction/train.csv')
recruit.loc[recruit['gender'] == 'M', 'gender'] = 1.0
recruit.loc[recruit['gender'] == 'F', 'gender'] = 0.0

recruit.loc[recruit['status'] == 'Placed', 'status'] = 1
recruit.loc[recruit['status'] == 'Not Placed', 'status'] = 0

recruit.loc[recruit['workex'] == 'Yes', 'workex'] = 1.0
recruit.loc[recruit['workex'] == 'No', 'workex'] = 0.0

recruit.loc[recruit['ssc_b'] == 'Central', 'ssc_b'] = 1.0
recruit.loc[recruit['ssc_b'] == 'Others', 'ssc_b'] = 0.0

recruit.loc[recruit['hsc_b'] == 'Central', 'hsc_b'] = 1.0
recruit.loc[recruit['hsc_b'] == 'Others', 'hsc_b'] = 0.0

recruit.loc[recruit['hsc_s'] == 'Science', 'hsc_s'] = 1.0
recruit.loc[recruit['hsc_s'] == 'Arts', 'hsc_s'] = 0.0
recruit.loc[recruit['hsc_s'] == 'Commerce', 'hsc_s'] = 0.0

recruit.loc[recruit['degree_t'] == 'Sci&Tech', 'degree_t'] = 1.0
recruit.loc[recruit['degree_t'] == 'Comm&Mgmt', 'degree_t'] = 0.0
recruit.loc[recruit['degree_t'] == 'Others', 'degree_t'] = 0.0

recruit.loc[recruit['specialisation'] == 'Mkt&HR', 'specialisation'] = 1.0
recruit.loc[recruit['specialisation'] == 'Mkt&Fin', 'specialisation'] = 0.0

recruit.head()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,0,67.00,0.0,91.00,0.0,0.0,58.00,1.0,0.0,55.0,1.0,58.80,1,270000.0
1,2,0,79.33,1.0,78.33,0.0,1.0,77.48,1.0,1.0,86.5,0.0,66.28,1,200000.0
2,3,0,65.00,1.0,68.00,1.0,0.0,64.00,0.0,0.0,75.0,0.0,57.80,1,250000.0
3,4,0,56.00,1.0,52.00,1.0,1.0,52.00,1.0,0.0,66.0,1.0,59.43,0,NaN
4,5,0,85.80,1.0,73.60,1.0,0.0,73.30,0.0,0.0,96.8,0.0,55.50,1,425000.0

In [4]:
x = recruit.drop(['status','salary'], axis=1)
y = recruit['status'].astype(float)

# split train and test dataset
train_x, test_x, train_y, test_y = train_test_split(x,y , test_size=0.3, random_state=42)

In [5]:
rf_regressor = RandomForestRegressor(200, oob_score=True,max_features='sqrt',
                                     n_jobs=-1, random_state=42,min_samples_leaf=1)
rf_regressor.fit(x,y)

RandomForestRegressor(max_features='sqrt', n_estimators=200, n_jobs=-1,
                      oob_score=True, random_state=42)

In [6]:
rf_classifier = RandomForestClassifier(200, oob_score=True,
                                     n_jobs=-1, random_state=42)
rf_classifier.fit(train_x, train_y)

pred_y = rf_classifier.predict(test_x)

In [7]:
pickle.dump(rf_classifier, open("model.pkl", "wb"))
pickle.dump(rf_regressor, open("model1.pkl", "wb"))